In [ ]:
# ndArray

import numpy as np

# 다차원 배열의 생성 역할
# 1차원 ndArray 생성
np.array([1, 2, 3, 4])

arr1 = np.array([1, 2, 3, 4]) # 넘파이 ndArray
arr2 = [1, 2, 3, 4] # 파이썬 리스트

print(type(arr1)) # 넘파이로 이루어진 다차원 배열
print(type(arr2)) # 그냥 리스트 형태

<class 'numpy.ndarray'>
<class 'list'>


In [6]:
# 2차원 ndArray 생성
# 1차원 배열 두개가 리스트로 묶인 형태가 2차원 배열이다.
arr2 = np.array([[1,2,3,4], 
                 [5,6,7,8]])

# 3차원 ndArray 생성
arr3 = np.array([[[1,2,3,4], [1,2,3,4]], 
                 [[1,2,3,4], [1,2,3,4]]])

print("2차원 배열 arr2")
print(arr2)

print("3차원 배열 arr3")
print(arr3)

2차원 배열 arr2
[[1 2 3 4]
 [5 6 7 8]]
3차원 배열 arr3
[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]
